[project]
name = "fresh-skills"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-core>=1.6.1",
    "langgraph>=1.2.11",
    "langsmith>=0.11.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.3",
    "jupytext>=1.19.5",
]

[tool.jupytext]
formats = "ipynb,py:percent"
